spring.application.name=samplePJ-TODO


spring.thymeleaf.mode=HTML


# パスワードハッシュ化方式
password.hash.code=SHA-256


# Postgres接続先設定
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=saisyuukadai


# ログレベル
logging.level.sample.*=DEBUG


# MyBatis設定
mybatis.type-aliases-package=sample.common.dao.entity
mybatis.mapper-locations=classpath:sample/common/dao/mapper/*.xml


# セッション有効期限設定
server.servlet.session.timeout=1d